# Generated by Django 5.0.8 on 2026-01-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('person_type', models.CharField(choices=[('individual', 'Физ. лицо'), ('company', 'Юр. лицо')], max_length=50, verbose_name='Тип клиента')),
                ('car', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автомобиль')),
                ('budget_from', models.BigIntegerField(blank=True, null=True, verbose_name='От')),
                ('budget_to', models.BigIntegerField(blank=True, null=True, verbose_name='До')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
